
export const languages: { code: string; name: string; direction: 'ltr' | 'rtl' }[] = [
    { "code": "ab", "name": "Abkhazian", "direction": "ltr" },
    { "code": "aa", "name": "Afar", "direction": "ltr" },
    { "code": "af", "name": "Afrikaans", "direction": "ltr" },
    { "code": "ak", "name": "Akan", "direction": "ltr" },
    { "code": "sq", "name": "Albanian", "direction": "ltr" },
    { "code": "am", "name": "Amharic", "direction": "ltr" },
    { "code": "ar", "name": "Arabic", "direction": "rtl" },
    { "code": "an", "name": "Aragonese", "direction": "ltr" },
    { "code": "hy", "name": "Armenian", "direction": "ltr" },
    { "code": "as", "name": "Assamese", "direction": "ltr" },
    { "code": "av", "name": "Avaric", "direction": "ltr" },
    { "code": "ae", "name": "Avestan", "direction": "ltr" },
    { "code": "ay", "name": "Aymara", "direction": "ltr" },
    { "code": "az", "name": "Azerbaijani", "direction": "ltr" },
    { "code": "bm", "name": "Bambara", "direction": "ltr" },
    { "code": "ba", "name": "Bashkir", "direction": "ltr" },
    { "code": "eu", "name": "Basque", "direction": "ltr" },
    { "code": "be", "name": "Belarusian", "direction": "ltr" },
    { "code": "bn", "name": "Bengali", "direction": "ltr" },
    { "code": "bh", "name": "Bihari languages", "direction": "ltr" },
    { "code": "bi", "name": "Bislama", "direction": "ltr" },
    { "code": "bs", "name": "Bosnian", "direction": "ltr" },
    { "code": "br", "name": "Breton", "direction": "ltr" },
    { "code": "bg", "name": "Bulgarian", "direction": "ltr" },
    { "code": "my", "name": "Burmese", "direction": "ltr" },
    { "code": "ca", "name": "Catalan, Valencian", "direction": "ltr" },
    { "code": "ch", "name": "Chamorro", "direction": "ltr" },
    { "code": "ce", "name": "Chechen", "direction": "ltr" },
    { "code": "ny", "name": "Chichewa, Chewa, Nyanja", "direction": "ltr" },
    { "code": "zh", "name": "Chinese", "direction": "ltr" },
    { "code": "cv", "name": "Chuvash", "direction": "ltr" },
    { "code": "kw", "name": "Cornish", "direction": "ltr" },
    { "code": "co", "name": "Corsican", "direction": "ltr" },
    { "code": "cr", "name": "Cree", "direction": "ltr" },
    { "code": "hr", "name": "Croatian", "direction": "ltr" },
    { "code": "cs", "name": "Czech", "direction": "ltr" },
    { "code": "da", "name": "Danish", "direction": "ltr" },
    { "code": "dv", "name": "Divehi, Dhivehi, Maldivian", "direction": "rtl" },
    { "code": "nl", "name": "Dutch, Flemish", "direction": "ltr" },
    { "code": "dz", "name": "Dzongkha", "direction": "ltr" },
    { "code": "en", "name": "English", "direction": "ltr" },
    { "code": "eo", "name": "Esperanto", "direction": "ltr" },
    { "code": "et", "name": "Estonian", "direction": "ltr" },
    { "code": "ee", "name": "Ewe", "direction": "ltr" },
    { "code": "fo", "name": "Faroese", "direction": "ltr" },
    { "code": "fj", "name": "Fijian", "direction": "ltr" },
    { "code": "fi", "name": "Finnish", "direction": "ltr" },
    { "code": "fr", "name": "French", "direction": "ltr" },
    { "code": "ff", "name": "Fulah", "direction": "ltr" },
    { "code": "gl", "name": "Galician", "direction": "ltr" },
    { "code": "ka", "name": "Georgian", "direction": "ltr" },
    { "code": "de", "name": "German", "direction": "ltr" },
    { "code": "el", "name": "Greek, Modern (1453–)", "direction": "ltr" },
    { "code": "gn", "name": "Guarani", "direction": "ltr" },
    { "code": "gu", "name": "Gujarati", "direction": "ltr" },
    { "code": "ht", "name": "Haitian, Haitian Creole", "direction": "ltr" },
    { "code": "ha", "name": "Hausa", "direction": "rtl" },
    { "code": "he", "name": "Hebrew", "direction": "rtl" },
    { "code": "hz", "name": "Herero", "direction": "ltr" },
    { "code": "hi", "name": "Hindi", "direction": "ltr" },
    { "code": "ho", "name": "Hiri Motu", "direction": "ltr" },
    { "code": "hu", "name": "Hungarian", "direction": "ltr" },
    { "code": "ia", "name": "Interlingua (International Auxiliary Language Association)", "direction": "ltr" },
    { "code": "id", "name": "Indonesian", "direction": "ltr" },
    { "code": "ie", "name": "Interlingue, Occidental", "direction": "ltr" },
    { "code": "ga", "name": "Irish", "direction": "ltr" },
    { "code": "ig", "name": "Igbo", "direction": "ltr" },
    { "code": "ik", "name": "Inupiaq", "direction": "ltr" },
    { "code": "io", "name": "Ido", "direction": "ltr" },
    { "code": "is", "name": "Icelandic", "direction": "ltr" },
    { "code": "it", "name": "Italian", "direction": "ltr" },
    { "code": "iu", "name": "Inuktitut", "direction": "ltr" },
    { "code": "ja", "name": "Japanese", "direction": "ltr" },
    { "code": "jv", "name": "Javanese", "direction": "ltr" },
    { "code": "kl", "name": "Kalaallisut, Greenlandic", "direction": "ltr" },
    { "code": "kn", "name": "Kannada", "direction": "ltr" },
    { "code": "kr", "name": "Kanuri", "direction": "ltr" },
    { "code": "ks", "name": "Kashmiri", "direction": "rtl" },
    { "code": "kk", "name": "Kazakh", "direction": "ltr" },
    { "code": "km", "name": "Central Khmer", "direction": "ltr" },
    { "code": "ki", "name": "Kikuyu, Gikuyu", "direction": "ltr" },
    { "code": "rw", "name": "Kinyarwanda", "direction": "ltr" },
    { "code": "ky", "name": "Kirghiz, Kyrgyz", "direction": "ltr" },
    { "code": "kv", "name": "Komi", "direction": "ltr" },
    { "code": "kg", "name": "Kongo", "direction": "ltr" },
    { "code": "ko", "name": "Korean", "direction": "ltr" },
    { "code": "ku", "name": "Kurdish", "direction": "rtl" },
    { "code": "kj", "name": "Kuanyama, Kwanyama", "direction": "ltr" },
    { "code": "la", "name": "Latin", "direction": "ltr" },
    { "code": "lb", "name": "Luxembourgish, Letzeburgesch", "direction": "ltr" },
    { "code": "lg", "name": "Ganda", "direction": "ltr" },
    { "code": "li", "name": "Limburgan, Limburger, Limburgish", "direction": "ltr" },
    { "code": "ln", "name": "Lingala", "direction": "ltr" },
    { "code": "lo", "name": "Lao", "direction": "ltr" },
    { "code": "lt", "name": "Lithuanian", "direction": "ltr" },
    { "code": "lu", "name": "Luba-Katanga", "direction": "ltr" },
    { "code": "lv", "name": "Latvian", "direction": "ltr" },
    { "code": "gv", "name": "Manx", "direction": "ltr" },
    { "code": "mk", "name": "Macedonian", "direction": "ltr" },
    { "code": "mg", "name": "Malagasy", "direction": "ltr" },
    { "code": "ms", "name": "Malay", "direction": "ltr" },
    { "code": "ml", "name": "Malayalam", "direction": "ltr" },
    { "code": "mt", "name": "Maltese", "direction": "ltr" },
    { "code": "mi", "name": "Maori", "direction": "ltr" },
    { "code": "mr", "name": "Marathi", "direction": "ltr" },
    { "code": "mh", "name": "Marshallese", "direction": "ltr" },
    { "code": "mn", "name": "Mongolian", "direction": "ltr" },
    { "code": "na", "name": "Nauru", "direction": "ltr" },
    { "code": "nv", "name": "Navajo, Navaho", "direction": "ltr" },
    { "code": "nd", "name": "North Ndebele", "direction": "ltr" },
    { "code": "ne", "name": "Nepali", "direction": "ltr" },
    { "code": "ng", "name": "Ndonga", "direction": "ltr" },
    { "code": "nb", "name": "Norwegian Bokmål", "direction": "ltr" },
    { "code": "nn", "name": "Norwegian Nynorsk", "direction": "ltr" },
    { "code": "no", "name": "Norwegian", "direction": "ltr" },
    { "code": "ii", "name": "Sichuan Yi, Nuosu", "direction": "ltr" },
    { "code": "nr", "name": "South Ndebele", "direction": "ltr" },
    { "code": "oc", "name": "Occitan", "direction": "ltr" },
    { "code": "oj", "name": "Ojibwa", "direction": "ltr" },
    { "code": "cu", "name": "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", "direction": "ltr" },
    { "code": "om", "name": "Oromo", "direction": "ltr" },
    { "code": "or", "name": "Oriya", "direction": "ltr" },
    { "code": "os", "name": "Ossetian, Ossetic", "direction": "ltr" },
    { "code": "pa", "name": "Panjabi, Punjabi", "direction": "ltr" },
    { "code": "pi", "name": "Pali", "direction": "ltr" },
    { "code": "fa", "name": "Persian", "direction": "rtl" },
    { "code": "pl", "name": "Polish", "direction": "ltr" },
    { "code": "ps", "name": "Pashto, Pushto", "direction": "rtl" },
    { "code": "pt", "name": "Portuguese", "direction": "ltr" },
    { "code": "qu", "name": "Quechua", "direction": "ltr" },
    { "code": "rm", "name": "Romansh", "direction": "ltr" },
    { "code": "rn", "name": "Rundi", "direction": "ltr" },
    { "code": "ro", "name": "Romanian, Moldavian, Moldovan", "direction": "ltr" },
    { "code": "ru", "name": "Russian", "direction": "ltr" },
    { "code": "sa", "name": "Sanskrit", "direction": "ltr" },
    { "code": "sc", "name": "Sardinian", "direction": "ltr" },
    { "code": "sd", "name": "Sindhi", "direction": "rtl" },
    { "code": "se", "name": "Northern Sami", "direction": "ltr" },
    { "code": "sm", "name": "Samoan", "direction": "ltr" },
    { "code": "sg", "name": "Sango", "direction": "ltr" },
    { "code": "sr", "name": "Serbian", "direction": "ltr" },
    { "code": "gd", "name": "Gaelic, Scottish Gaelic", "direction": "ltr" },
    { "code": "sn", "name": "Shona", "direction": "ltr" },
    { "code": "si", "name": "Sinhala, Sinhalese", "direction": "ltr" },
    { "code": "sk", "name": "Slovak", "direction": "ltr" },
    { "code": "sl", "name": "Slovenian", "direction": "ltr" },
    { "code": "so", "name": "Somali", "direction": "ltr" },
    { "code": "st", "name": "Southern Sotho", "direction": "ltr" },
    { "code": "es", "name": "Spanish, Castilian", "direction": "ltr" },
    { "code": "su", "name": "Sundanese", "direction": "ltr" },
    { "code": "sw", "name": "Swahili", "direction": "ltr" },
    { "code": "ss", "name": "Swati", "direction": "ltr" },
    { "code": "sv", "name": "Swedish", "direction": "ltr" },
    { "code": "ta", "name": "Tamil", "direction": "ltr" },
    { "code": "te", "name": "Telugu", "direction": "ltr" },
    { "code": "tg", "name": "Tajik", "direction": "ltr" },
    { "code": "th", "name": "Thai", "direction": "ltr" },
    { "code": "ti", "name": "Tigrinya", "direction": "ltr" },
    { "code": "bo", "name": "Tibetan", "direction": "ltr" },
    { "code": "tk", "name": "Turkmen", "direction": "ltr" },
    { "code": "tl", "name": "Tagalog", "direction": "ltr" },
    { "code": "tn", "name": "Tswana", "direction": "ltr" },
    { "code": "to", "name": "Tonga (Tonga Islands)", "direction": "ltr" },
    { "code": "tr", "name": "Turkish", "direction": "ltr" },
    { "code": "ts", "name": "Tsonga", "direction": "ltr" },
    { "code": "tt", "name": "Tatar", "direction": "ltr" },
    { "code": "tw", "name": "Twi", "direction": "ltr" },
    { "code": "ty", "name": "Tahitian", "direction": "ltr" },
    { "code": "ug", "name": "Uighur, Uyghur", "direction": "rtl" },
    { "code": "uk", "name": "Ukrainian", "direction": "ltr" },
    { "code": "ur", "name": "Urdu", "direction": "rtl" },
    { "code": "uz", "name": "Uzbek", "direction": "ltr" },
    { "code": "ve", "name": "Venda", "direction": "ltr" },
    { "code": "vi", "name": "Vietnamese", "direction": "ltr" },
    { "code": "vo", "name": "Volapük", "direction": "ltr" },
    { "code": "wa", "name": "Walloon", "direction": "ltr" },
    { "code": "cy", "name": "Welsh", "direction": "ltr" },
    { "code": "wo", "name": "Wolof", "direction": "ltr" },
    { "code": "fy", "name": "Western Frisian", "direction": "ltr" },
    { "code": "xh", "name": "Xhosa", "direction": "ltr" },
    { "code": "yi", "name": "Yiddish", "direction": "rtl" },
    { "code": "yo", "name": "Yoruba", "direction": "ltr" },
    { "code": "za", "name": "Zhuang, Chuang", "direction": "ltr" },
    { "code": "zu", "name": "Zulu", "direction": "ltr" }
]

    